version: '3.1'

services:

  db:
    container_name: work-dist-api-db
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c@sUser1
      MYSQL_DATABASE: db_example
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: c@sUser1
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: work-dist-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data:
