insert into db_example.agent(agent_id,first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (1,'Agent1', 'Test1', 'Y', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (2,'Agent2', 'Test2', 'Y', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (3,'Agent3', 'Test3', 'Y', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (4,'Agent4', 'Test4', 'Y', 'Y', 'N', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (5,'Agent5', 'Test5', 'Y', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (6,'Agent6', 'Test6', 'N', 'Y', 'N', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (7,'Agent7', 'Test7', 'N', 'N', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (8,'Agent8', 'Test8', 'N', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (9,'Agent9', 'Test9', 'Y', 'N', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (10,'Agent10', 'Test10', 'Y', 'Y', 'N', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (11,'Agent11', 'Test11', 'Y', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (12,'Agent12', 'Test12', 'N', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (13,'Agent13', 'Test13', 'Y', 'N', 'N', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (14,'Agent14', 'Test14', 'Y', 'N', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (15,'Agent15', 'Test15', 'Y', 'Y', 'N', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (16,'Agent16', 'Test16', 'Y', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (17,'Agent17', 'Test17', 'N', 'Y', 'Y', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (18,'Agent18', 'Test18', 'Y', 'N', 'N', now(), now());
insert into db_example.agent(agent_id, first_name, last_name, skill1, skill2, skill3, created_at, updated_at) values (19,'Agent19', 'Test19', 'Y', 'Y', 'N', now(), now());

